name: BuildAndPushImageOnHarborAndUpdateArgoCDConfig

on:
  push:
    branches: [ "testing" ]

jobs:
  update-captcha-bypass-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger captcha bypass to  scan repo dispatch event
        run: |
          curl -i -X POST https://api.github.com/repos/s4e-io/s4e-scan/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GH_ACCESS_TOKEN }}" \
            -d '{"event_type": "captcha-bypass-update", "client_payload": {"branch": "testing"}}'
